language: R
sudo: required
cache: packages
warnings_are_errors: false

before_install:
  - sudo apt-get install -y libhdf5-dev

r:
  - release
  - devel

r_packages:
  - knitr
  - devtools
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
